### ISSUE TITLE
تغییر فونت داکیومنت

### ISSUE THREAD

**Issue by hbsoftco** [vuejs-fa/fa.vuejs.org#13]
اگر ممکنه یه فونت خوب هم ست بشه خیلی خوب میشد
فونت دیفالتش خیلی چشم رو اذیت می کنه

**Comment by Goudarz** [comment]
فونت فارسی نصب شده و در حال حاضر به صورت پیش‌فرض فونت وزیر می‌باشد 
[#14](https://github.com/vuejs-fa/fa.vuejs.org/pull/14)
